Repository Javacord/Javacord, pull requests merged in 2018-12, with the labels that each got.

#404 Do not send requests after DiscordApi#disconnect was called or the OkHttp threads hang again with Java 9+
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
Labels: medium priority

#405 Fix User#getMutualServers() performance bottleneck
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/entity/user/User.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
Labels: high priority

#410 Revert the CircleCI tweaks
  .circleci/config.yml
Labels: low priority

#408 Add a generic getListeners method for getting all registered globally attachable listerners of a given type and move most implementations of GloballyAttachableListenerManager methods into default methods neglecting the need for the InternalGloballyAttachableListenerManager
  gradle/listener-manager-generation.gradle
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
Labels: low priority

#414 Make code generation throw meaningful errors in case of unexpected inheritance
  gradle/event-dispatcher-generation.gradle
  gradle/listener-manager-generation.gradle
Labels: low priority

#415 Prevent ConcurrentModificationExceptions during testing
  javacord-core/src/test/groovy/org/javacord/core/DiscordApiImplTest.groovy
  javacord-core/src/test/groovy/org/javacord/core/util/gateway/DiscordWebSocketAdapterTest.groovy
  javacord-core/src/test/groovy/org/javacord/core/util/ratelimit/RatelimitManagerTest.groovy
Labels: low priority

#416 ServerChannel should extend Comparable
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerChannel.java
Labels: low priority
