Repository Javacord/Javacord, pull requests merged in 2018-10, with the labels that each got.

#381 Add missing overrides in ChannelCategoryBuilder
  javacord-api/src/main/java/org/javacord/api/entity/channel/ChannelCategoryBuilder.java
Labels: medium priority

#387 Add slowmode support.
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannelBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannelUpdater.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerTextChannelBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerTextChannelUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/event/channel/server/text/ServerTextChannelChangeSlowmodeEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/channel/server/text/ServerTextChannelChangeSlowmodeListener.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/server/text/ServerTextChannelChangeSlowmodeEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
Labels: high priority

#391 Do not use the proxy url when downloading attachments
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageAttachmentImpl.java
Labels: high priority

#393 Generalize asFoo methods
  javacord-api/src/main/java/org/javacord/api/entity/channel/Categorizable.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/Channel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ChannelSpecialization.java
  javacord-api/src/main/java/org/javacord/api/entity/emoji/Emoji.java
  javacord-api/src/main/java/org/javacord/api/util/Specializable.java
Labels: low priority

#389 Allow requesting an emojis creator.
  javacord-api/src/main/java/org/javacord/api/entity/emoji/KnownCustomEmoji.java
  javacord-core/src/main/java/org/javacord/core/entity/emoji/KnownCustomEmojiImpl.java
Labels: high priority

#392 Add convenience methods for messages
  .github/README.md.sha256
  .github/README_template.md
  README.md
  javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
  javacord-api/src/main/java/org/javacord/api/event/message/CertainMessageEvent.java
  javacord-api/src/main/java/org/javacord/api/event/message/OptionalMessageEvent.java
Labels: low priority
