Repository Javacord/Javacord, pull requests merged in 2018-08, with the labels that each got.

#352 Release Process Improvements
  build.gradle
  gradle/publishing.gradle
Labels: medium priority

#322 Make EventDispatcher thread-safe and rework some of its synchronization code
  javacord-core/src/main/java/org/javacord/core/util/event/EventDispatcherBase.java
Labels: medium priority

#366 Reworked ratelimit handling
  javacord-core/src/main/java/org/javacord/core/AccountUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/InternalTextChannel.java
  javacord-core/src/main/java/org/javacord/core/entity/message/UncachedMessageUtilImpl.java
  javacord-core/src/main/java/org/javacord/core/util/ratelimit/RatelimitBucket.java
  javacord-core/src/main/java/org/javacord/core/util/ratelimit/RatelimitManager.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequest.java
Labels: high priority

#367 Some smaller tweaks to the readme
  .github/README.md.sha256
  .github/README_template.md
  README.md
Labels: low priority

#219 Use SoftReferences in the MessageCache to release memory if needed and make it possible to disable automatic cache cleanup
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/util/cache/MessageCache.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/GroupChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/PrivateChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
  javacord-core/src/main/java/org/javacord/core/util/cache/MessageCacheImpl.java
Labels: low priority

#368 Added link to Intellij & Gradle setup tutorial
  .github/README.md.sha256
  .github/README_template.md
  README.md
Labels: low priority

#373 Replace log4j version from dependencies into readme template
  .github/README_template.md
  gradle/readme.gradle
Labels: low priority
