Repository Javacord/Javacord, pull requests merged in 2019-03, with the labels that each got.

#445 Added static method to build Permissions from permission Bitmasks
  javacord-api/src/main/java/org/javacord/api/entity/permission/Permissions.java
Labels: low priority

#452 Update checkstyle document type definitions
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: low priority

#451 Add tts flag for received messages
  javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
Labels: medium priority

#441 Added ban request methods to ServerMemberBanEvent
  javacord-api/src/main/java/org/javacord/api/event/server/member/ServerMemberBanEvent.java
  javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMemberBanEventImpl.java
Labels: low priority

#457 Ignore presences for users that do not exist in the members field
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
Labels: high priority

#456 Increase load wait time for new servers to become available
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
Labels: high priority

#459 Fix unknown role exception on channel updates
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
Labels: high priority

#455 Improve performance of getters for channels
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/GroupChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/PrivateChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelDeleteHandler.java
Labels: high priority

#434 Fix Emoji comparison
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
Labels: medium priority

#461 Quickfix for new channel types
  javacord-api/src/main/java/org/javacord/api/entity/channel/ChannelType.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/ReadyHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelCreateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelDeleteHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
Labels: medium priority
