Repository Javacord/Javacord, pull requests merged in 2019-01, with the labels that each got.

#420 Harden RateLimitManager against NPE from missing response.
  javacord-core/src/main/java/org/javacord/core/util/ratelimit/RatelimitManager.java
Labels: medium priority

#424 Catch Throwable instead of Exception when handling packets
  javacord-core/src/main/java/org/javacord/core/util/gateway/PacketHandler.java
Labels: medium priority

#421 Remove object listeners on channel/server/message deletion.
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelDeleteHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildDeleteHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageDeleteHandler.java
Labels: low priority

#400 Implemented Role utility methods
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/entity/user/User.java
Labels: medium priority

#427 Update websocket dependency
  gradle/dependencies.gradle
  javacord-core/src/main/java/org/javacord/core/util/logging/WebSocketLogger.java
  javacord-core/src/test/resources/mockserver.properties
Labels: high priority

#426 Support for mobile indicator
  javacord-api/src/main/java/org/javacord/api/entity/DiscordClient.java
  javacord-api/src/main/java/org/javacord/api/entity/user/User.java
  javacord-api/src/main/java/org/javacord/api/event/user/UserChangeStatusEvent.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/user/UserImpl.java
  javacord-core/src/main/java/org/javacord/core/event/user/UserChangeStatusEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/user/PresenceUpdateHandler.java
Labels: high priority
