Repository Javacord/Javacord, pull requests merged in 2020-04, with the labels that each got.

#514 Convenience method to get display color of a MessageAuthor
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageAuthor.java
Labels: low priority

#499 Implement priority speaker
  javacord-api/src/main/java/org/javacord/api/audio/AudioConnection.java
  javacord-api/src/main/java/org/javacord/api/audio/SpeakingFlag.java
  javacord-core/src/main/java/org/javacord/core/audio/AudioConnectionImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioWebSocketAdapter.java
Labels: audio, high priority

#525 Allowed mentions
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/internal/MessageBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/message/mention/AllowedMentions.java
  javacord-api/src/main/java/org/javacord/api/entity/message/mention/AllowedMentionsBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/mention/internal/AllowedMentionsBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactory.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactoryDelegate.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/mention/AllowedMentionsBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/mention/AllowedMentionsImpl.java
  javacord-core/src/main/java/org/javacord/core/util/DelegateFactoryDelegateImpl.java
Labels: medium priority

#529 Cleanup contribution guidelines
  .github/CONTRIBUTING.md
Labels: low priority

#447 Make FileContainer#asInputStream return an InputStream directly
  javacord-core/src/main/java/org/javacord/core/entity/IconImpl.java
  javacord-core/src/main/java/org/javacord/core/util/FileContainer.java
  javacord-core/src/test/groovy/org/javacord/core/util/FileContainerTest.groovy
Labels: low priority

#500 Implement Voice State/Server Update events
  javacord-api/src/main/java/org/javacord/api/event/server/VoiceServerUpdateEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/VoiceStateUpdateEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/server/VoiceServerUpdateListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/VoiceStateUpdateListener.java
  javacord-core/src/main/java/org/javacord/core/event/server/VoiceServerUpdateEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/VoiceStateUpdateEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceServerUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceStateUpdateHandler.java
Labels: audio, high priority
