Repository Javacord/Javacord, pull requests merged in 2020-05, with the labels that each got.

#534 fix for Server#canManageRole
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
Labels: medium priority

#539 Fix AudioConnection#setSpeaking(boolean) method
  javacord-api/src/main/java/org/javacord/api/audio/AudioConnection.java
  javacord-core/src/main/java/org/javacord/core/audio/AudioConnectionImpl.java
Labels: medium priority

#535 Message#getLink method.
  javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/event/message/CertainMessageEvent.java
  javacord-api/src/main/java/org/javacord/api/event/message/OptionalMessageEvent.java
Labels: low priority

#531 Added method to get reaction tag of custom emoji
  javacord-api/src/main/java/org/javacord/api/entity/emoji/CustomEmoji.java
  javacord-core/src/main/java/org/javacord/core/entity/message/UncachedMessageUtilImpl.java
Labels: low priority

#486 Role performance & synchronization enhancements
  javacord-api/src/main/java/org/javacord/api/entity/permission/Role.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-core/src/main/java/org/javacord/core/entity/permission/RoleImpl.java
Labels: medium priority

#425 Allow to attach MessageCreateListeners to Webhooks
  gradle/event-dispatcher-generation.gradle
  javacord-api/src/main/java/org/javacord/api/entity/webhook/Webhook.java
  javacord-api/src/main/java/org/javacord/api/listener/message/MessageCreateListener.java
  javacord-api/src/main/java/org/javacord/api/listener/webhook/WebhookAttachableListener.java
  javacord-core/src/main/java/org/javacord/core/entity/webhook/WebhookImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
Labels: low priority

#544 Fix typo in comment
  javacord-core/src/main/java/org/javacord/core/entity/emoji/KnownCustomEmojiImpl.java
Labels: low priority

#536 method to get Message by link
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/util/DiscordRegexPattern.java
Labels: low priority

#547 Fixes wrong InviteImpl logger class
  javacord-core/src/main/java/org/javacord/core/entity/server/invite/InviteImpl.java
Labels: low priority

#549 Add MessageAuthor#getConnectedVoiceChannel()
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageAuthor.java
Labels: low priority

#550 Fix parsing exception for invalid Discord response
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestResult.java
Labels: medium priority

#551 Fix wrong snapshot version
  gradle.properties
Labels: medium priority

#437 Adds MessageAttachment#downloadAsInputStream
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageAttachment.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageAttachmentImpl.java
Labels: low priority

#557 Enhance ChannelType with more information
  javacord-api/src/main/java/org/javacord/api/entity/channel/ChannelType.java
Labels: low priority

#553 Improve readme template
  .github/README_template.md
Labels: low priority

#423 Role order and sorting changes.
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/permission/Role.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/event/server/role/RoleChangePositionEvent.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ChannelCategoryImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/permission/RoleImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/role/RoleChangePositionEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/role/GuildRoleUpdateHandler.java
Labels: medium priority

#561 Housekeeping
  config/checkstyle/checkstyle.xml
  gradle/listener-manager-generation.gradle
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/entity/webhook/Webhook.java
  javacord-api/src/main/java/org/javacord/api/util/auth/Authenticator.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/embed/EmbedAuthorImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/server/voice/ServerVoiceChannelMemberJoinEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/server/voice/ServerVoiceChannelMemberLeaveEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/cache/MessageCacheImpl.java
  javacord-core/src/main/java/org/javacord/core/util/event/EventDispatcherBase.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildCreateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/logging/ExceptionLoggerDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/ratelimit/RatelimitManager.java
Labels: low priority

#555 Change the occourences of discordapp.com to discord.com
  javacord-api/src/main/java/org/javacord/api/BotInviteBuilder.java
  javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
  javacord-api/src/main/java/org/javacord/api/Javacord.java
  javacord-api/src/main/java/org/javacord/api/entity/DiscordEntity.java
  javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityType.java
  javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerBecomesAvailableEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerBecomesUnavailableEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerBecomesAvailableListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerBecomesUnavailableListener.java
  javacord-api/src/main/java/org/javacord/api/util/DiscordRegexPattern.java
  javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityAssetsImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/auditlog/AuditLogEntryImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/GroupChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/emoji/CustomEmojiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/invite/InviteImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/user/UserImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/webhook/WebhookImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeIconEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeSplashEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/GatewayOpcode.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/VoiceGatewayOpcode.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/WebSocketCloseCode.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestEndpoint.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestHttpResponseCode.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestResultErrorCode.java
  javacord-core/src/test/resources/mockserver.properties
Labels: high priority

#563 Add code of conduct
  .github/CODE_OF_CONDUCT.md
Labels: low priority

#545 Adding missing server fields to Server and ServerUpdater
  javacord-api/src/main/java/org/javacord/api/entity/VanityUrlCode.java
  javacord-api/src/main/java/org/javacord/api/entity/server/BoostLevel.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/entity/server/ServerFeature.java
  javacord-api/src/main/java/org/javacord/api/entity/server/ServerUpdater.java
  javacord-api/src/main/java/org/javacord/api/entity/server/internal/ServerUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeBoostCountEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeBoostLevelEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeDescriptionEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeDiscoverySplashEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeModeratorsOnlyChannelEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangePreferredLocaleEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeRulesChannelEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeServerFeaturesEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeVanityUrlCodeEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeBoostCountListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeBoostLevelListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeDescriptionListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeDiscoverySplashListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeModeratorsOnlyChannelListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangePreferredLocaleListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeRulesChannelListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeServerFeatureListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeVanityUrlCodeListener.java
  javacord-core/src/main/java/org/javacord/core/entity/VanityUrlCodeImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeBoostCountEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeBoostLevelEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeDescriptionEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeDiscoverySplashEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeModeratorsOnlyChannelEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangePreferredLocaleEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeRulesChannelEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeServerFeaturesEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeVanityUrlCodeEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildUpdateHandler.java
Labels: medium priority

#556 Rework entity cache
  gradle/dependencies.gradle
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/util/ImmutableToJavaMapper.java
  javacord-core/src/main/java/org/javacord/core/util/cache/Cache.java
  javacord-core/src/main/java/org/javacord/core/util/cache/ChannelCache.java
  javacord-core/src/main/java/org/javacord/core/util/cache/Index.java
  javacord-core/src/main/java/org/javacord/core/util/cache/JavacordEntityCache.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelDeleteHandler.java
  javacord-core/src/main/java9/module-info.java
Labels: high priority

#569 Add DiscordApi#measureRestLatency()
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
Labels: low priority

#503 Replace AudioConnection#queue methods with AudioConnection#set methods
  javacord-api/src/main/java/org/javacord/api/audio/AudioConnection.java
  javacord-core/src/main/java/org/javacord/core/audio/AudioConnectionImpl.java
  javacord-core/src/main/java/org/javacord/core/util/concurrent/BlockingReference.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
Labels: audio, medium priority

#567 Vavr set view
  javacord-core/src/main/java/org/javacord/core/util/ImmutableToJavaMapper.java
  javacord-core/src/main/java/org/javacord/core/util/VavrSetView.java
Labels: medium priority
