Repository Javacord/Javacord, pull requests merged in 2020-09, with the labels that each got.

#579 Allow for more precise local ratelimits
  javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
Labels: medium priority

#580 Add default global ratelimiter
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
Labels: medium priority

#584 Add ActivityType.CUSTOM
  javacord-api/src/main/java/org/javacord/api/entity/activity/Activity.java
  javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityType.java
  javacord-core/src/main/java/org/javacord/core/entity/activity/ActivityImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
  javacord-core/src/main/java/org/javacord/core/util/handler/user/PresenceUpdateHandler.java
Labels: medium priority

#585 BoostLevel TIER_3 Id Bugfix
  javacord-api/src/main/java/org/javacord/api/entity/server/BoostLevel.java
Labels: medium priority

#591 Fix DiscordRegexPatter.MESSAGE_LINK
  javacord-api/src/main/java/org/javacord/api/util/DiscordRegexPattern.java
Labels: low priority

#594 Fix can manage role
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
Labels: medium priority

#600 Server Feature
  javacord-api/src/main/java/org/javacord/api/entity/server/ServerFeature.java
Labels: medium priority

#586 Audio Reconnecting
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioWebSocketAdapter.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/WebSocketCloseCode.java
Labels: high priority

#604 Prevent non-lifecycle frame sends when not fully connected
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/WebSocketFrameSendingQueueEntry.java
Labels: high priority

#606 Remove "Current" from #<set/get/remove>CurrentAudioSource() method name
  javacord-api/src/main/java/org/javacord/api/audio/AudioConnection.java
  javacord-api/src/main/java/org/javacord/api/event/audio/AudioSourceFinishedEvent.java
  javacord-core/src/main/java/org/javacord/core/audio/AudioConnectionImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
Labels: low priority

#607 Remove AudioSourceFinishedEvent#getNextSource()
  javacord-api/src/main/java/org/javacord/api/event/audio/AudioSourceFinishedEvent.java
Labels: low priority

#608 Add getter for ratelimit buckets
  javacord-core/src/main/java/org/javacord/core/util/ratelimit/RatelimitManager.java
Labels: low priority

#610 Add audio reconnect logic for dropped main gateway session
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/audio/AudioConnectionImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioWebSocketAdapter.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceServerUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceStateUpdateHandler.java
Labels: audio, high priority

#602 Add option to disable shutdown hook in DiscordApiBuilder
  javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
  javacord-api/src/main/java/org/javacord/api/internal/DiscordApiBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
Labels: medium priority

#532 Support for intents
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/intent/Intent.java
  javacord-api/src/main/java/org/javacord/api/internal/DiscordApiBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
  javacord-core/src/test/groovy/org/javacord/core/DiscordApiImplTest.groovy
Labels: high priority

#622 Fix Server#isMember(User)
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
Labels: high priority

#623 Fix performance bottleneck on login
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
Labels: high priority

#624 Improve performance of User#getMutualServers()
  javacord-api/src/main/java/org/javacord/api/entity/user/User.java
  javacord-core/src/main/java/org/javacord/core/entity/user/UserImpl.java
  javacord-core/src/main/java/org/javacord/core/util/cache/MemberCache.java
Labels: medium priority

#625 Fix TypingStartHandler for private messages
  javacord-core/src/main/java/org/javacord/core/util/handler/user/TypingStartHandler.java
Labels: high priority

#626 Disable waiting for users with GUILD_PRESENCES intent set
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
Labels: high priority

#627 Remove disconnect on unanswered heartbeat ack
  javacord-core/src/main/java/org/javacord/core/util/gateway/Heart.java
Labels: high priority

#621 Fix wrong warning about uncached members
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildMemberUpdateHandler.java
Labels: medium priority

#628 Control user waiting
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/internal/DiscordApiBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
  javacord-core/src/test/groovy/org/javacord/core/DiscordApiImplTest.groovy
Labels: high priority

#631 Fix #waitForUsersOnStartup()
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
Labels: high priority

#632 Re-add missing UserImpl#equals(...) override
  javacord-core/src/main/java/org/javacord/core/entity/user/UserImpl.java
Labels: high priority

#633 Fix ServerVoiceChannelMemberEvent
  javacord-core/src/main/java/org/javacord/core/event/channel/server/voice/ServerVoiceChannelMemberEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/server/voice/ServerVoiceChannelMemberJoinEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/server/voice/ServerVoiceChannelMemberLeaveEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceStateUpdateHandler.java
Labels: high priority
