Repository Javacord/Javacord, pull requests merged in 2020-12, with the labels that each got.

#662 Use member object as SSOT for role membership
  javacord-core/src/main/java/org/javacord/core/entity/permission/RoleImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/user/Member.java
  javacord-core/src/main/java/org/javacord/core/entity/user/MemberImpl.java
Labels: high priority

#619 Allow custom gateway identify ratelimiters
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
  javacord-api/src/main/java/org/javacord/api/internal/DiscordApiBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
  javacord-core/src/test/groovy/org/javacord/core/DiscordApiImplTest.groovy
Labels: medium priority

#448 Make Icon#asInputStream return an InputStream directly
  javacord-api/src/main/java/org/javacord/api/entity/Icon.java
  javacord-core/src/main/java/org/javacord/core/entity/IconImpl.java
Labels: breaking-change, low priority

#587 Fix and cleanup of Allowed Mentions
  javacord-api/src/main/java/org/javacord/api/entity/message/mention/AllowedMentionType.java
  javacord-api/src/main/java/org/javacord/api/entity/message/mention/AllowedMentions.java
  javacord-api/src/main/java/org/javacord/api/entity/message/mention/AllowedMentionsBuilder.java
  javacord-core/src/main/java/org/javacord/core/entity/message/mention/AllowedMentionsImpl.java
Labels: breaking-change, medium priority

#616 Inviter fix
  javacord-api/src/main/java/org/javacord/api/entity/server/invite/Invite.java
  javacord-api/src/main/java/org/javacord/api/entity/server/invite/RichInvite.java
  javacord-api/src/main/java/org/javacord/api/entity/server/invite/TargetUserType.java
  javacord-core/src/main/java/org/javacord/core/entity/server/invite/InviteImpl.java
Labels: breaking-change
