Repository Javacord/Javacord, pull requests merged in 2021-04, with the labels that each got.

#692 allow multiple activities
  javacord-api/src/main/java/org/javacord/api/entity/user/User.java
  javacord-api/src/main/java/org/javacord/api/event/user/UserChangeActivityEvent.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/user/UserImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/user/UserPresence.java
  javacord-core/src/main/java/org/javacord/core/event/user/UserChangeActivityEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/user/PresenceUpdateHandler.java
Labels: high priority

#685 Move user updates from PresenceUpdateHandler to GuildMemberUpdateHandler
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildMemberUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/user/PresenceUpdateHandler.java
Labels: medium priority

#708 compensate missing CHANNEL_CREATE event for text channels
  javacord-api/src/main/java/org/javacord/api/entity/channel/Channel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/PrivateChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextChannel.java
  javacord-api/src/main/java/org/javacord/api/event/channel/user/PrivateChannelEvent.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/PrivateChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/user/PrivateChannelEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/cache/ChannelCache.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelCreateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelPinsUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/WebhooksUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceStateUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageDeleteBulkHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageDeleteHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionAddHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveAllHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveHandler.java
  javacord-core/src/main/java/org/javacord/core/util/logging/LoggerUtil.java
  javacord-core/src/main/java/org/javacord/core/util/logging/PrivacyProtectionLogger.java
Labels: breaking-change, high priority

#730 Added new message types
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageType.java
Labels: low priority

#743 Fix failing channel update for SERVER_NEWS_CHANNEL
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
Labels: bug, low priority

#747 Added missing http error response codes
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestResultErrorCode.java
Labels: low priority

#738 Added role tags
  javacord-api/src/main/java/org/javacord/api/entity/permission/Role.java
  javacord-api/src/main/java/org/javacord/api/entity/permission/RoleTags.java
  javacord-core/src/main/java/org/javacord/core/entity/permission/RoleImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/permission/RoleTagsImpl.java
Labels: low priority

#675 Add support for application commands
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommand.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandBuilder.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandInteractionData.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandInteractionDataOption.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandOption.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandOptionBuilder.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandOptionChoice.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandOptionChoiceBuilder.java
  javacord-api/src/main/java/org/javacord/api/command/ApplicationCommandOptionType.java
  javacord-api/src/main/java/org/javacord/api/command/Interaction.java
  javacord-api/src/main/java/org/javacord/api/command/InteractionApplicationCommandCallbackData.java
  javacord-api/src/main/java/org/javacord/api/command/InteractionResponse.java
  javacord-api/src/main/java/org/javacord/api/command/InteractionResponseType.java
  javacord-api/src/main/java/org/javacord/api/command/InteractionType.java
  javacord-api/src/main/java/org/javacord/api/command/internal/ApplicationCommandBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/command/internal/ApplicationCommandOptionBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/command/internal/ApplicationCommandOptionChoiceBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/event/channel/server/ServerChannelEvent.java
  javacord-api/src/main/java/org/javacord/api/event/channel/server/text/ServerTextChannelEvent.java
  javacord-api/src/main/java/org/javacord/api/event/command/InteractionCreateEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/command/InteractionCreateListener.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactory.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactoryDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandInteractionDataImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandInteractionDataOptionImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandOptionBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandOptionChoiceBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandOptionChoiceImpl.java
  javacord-core/src/main/java/org/javacord/core/command/ApplicationCommandOptionImpl.java
  javacord-core/src/main/java/org/javacord/core/command/InteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/event/command/InteractionCreateEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/DelegateFactoryDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
  javacord-core/src/main/java/org/javacord/core/util/handler/command/InteractionCreateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestEndpoint.java
Labels: medium priority
