Repository Javacord/Javacord, pull requests merged in 2021-10, with the labels that each got.

#873 Wrong used methods in UncachedMessageUtil which cause an infinite loop
  javacord-api/src/main/java/org/javacord/api/entity/message/UncachedMessageUtil.java
Labels: bug, high priority

#860 Fix message cache deadlock by using central lock
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/util/cache/MessageCacheImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildMemberUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/role/GuildRoleUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageDeleteHandler.java
Labels: bug, high priority

#871 Replaced MessageFlag with InteractionCallbackDataFlag for interaction response types
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageFlag.java
  javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionCallbackDataFlag.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilderBase.java
  javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionMessageBuilderBaseImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionOriginalResponseUpdaterImpl.java
Labels: medium priority, breaking-change, hacktoberfest-accepted

#870 Add ephemeral field for attachments
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageAttachment.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageAttachmentImpl.java
Labels: hacktoberfest-accepted

#869 Add new appender types to the MessageBuilder.
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilderBase.java
  javacord-api/src/main/java/org/javacord/api/entity/message/TimestampStyle.java
  javacord-api/src/main/java/org/javacord/api/entity/message/internal/MessageBuilderBaseDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilderBase.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionMessageBuilderBaseImpl.java
Labels: hacktoberfest-accepted
