Repository Javacord/Javacord, pull requests merged in 2021-06, with the labels that each got.

#765 Add Github Action for building and testing
  .github/workflows/main.yml
Labels: low priority

#764 Add GitHub Action for codestyle checks
  .github/workflows/checkstyle.yml
Labels: low priority

#766 Added missing RestRequestResultErrorCode
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestResultErrorCode.java
Labels: low priority

#773 Add get server application commands
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestEndpoint.java
Labels: high priority

#739 Add USE_SLASH_COMMANDS permission type
  javacord-api/src/main/java/org/javacord/api/entity/permission/PermissionType.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
Labels: low priority

#774 Add methods to update application commands
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandUpdater.java
  javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactory.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactoryDelegate.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandOptionBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/DelegateFactoryDelegateImpl.java
Labels: high priority

#775 Add several component convenience methods
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/Messageable.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/ActionRow.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/ButtonBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/internal/MessageBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandOption.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandOptionChoice.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
Labels: high priority

#768 Rework of interaction responses
  javacord-api/src/main/java/org/javacord/api/entity/message/InteractionMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/event/interaction/InteractionCreateEvent.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandInteraction.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandInteractionData.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandInteractionOption.java
  javacord-api/src/main/java/org/javacord/api/interaction/ButtonInteraction.java
  javacord-api/src/main/java/org/javacord/api/interaction/Interaction.java
  javacord-api/src/main/java/org/javacord/api/interaction/InteractionBase.java
  javacord-api/src/main/java/org/javacord/api/interaction/InteractionComponentData.java
  javacord-api/src/main/java/org/javacord/api/interaction/InteractionData.java
  javacord-api/src/main/java/org/javacord/api/interaction/InteractionResponse.java
  javacord-api/src/main/java/org/javacord/api/interaction/InteractionResponseType.java
  javacord-api/src/main/java/org/javacord/api/interaction/MessageComponentInteraction.java
  javacord-api/src/main/java/org/javacord/api/interaction/MessageComponentInteractionBase.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/ComponentInteractionOriginalMessageUpdater.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/ExtendedInteractionMessageBuilderBase.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionFollowupMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionImmediateResponseBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilderBase.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionOriginalResponseUpdater.java
  javacord-api/src/main/java/org/javacord/api/util/SafeSpecializable.java
  javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/event/interaction/InteractionCreateEventImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandInteractionDataImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandInteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandInteractionOptionImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ButtonInteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ComponentInteractionOriginalMessageUpdaterImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ExtendedInteractionMessageBuilderBaseImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionComponentDataImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionFollowupMessageBuilderImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionImmediateResponseBuilderImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionMessageBuilderBaseImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionOriginalResponseUpdaterImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/MessageComponentInteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java
Labels: high priority

#776 Add bulk overwrite methods to update and/or create multiple application commands at once
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandUpdater.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandBuilderDelegateImpl.java
Labels: high priority

#779 Add the ability to modify the application command permissions
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissionType.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissions.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissionsBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissionsUpdater.java
  javacord-api/src/main/java/org/javacord/api/interaction/ServerApplicationCommandPermissions.java
  javacord-api/src/main/java/org/javacord/api/interaction/ServerApplicationCommandPermissionsBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandPermissionsBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandPermissionsUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactory.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactoryDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandPermissionsBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandPermissionsImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandPermissionsUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ServerApplicationCommandPermissionsImpl.java
  javacord-core/src/main/java/org/javacord/core/util/DelegateFactoryDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestEndpoint.java
Labels: high priority

#777 Add interaction convenience methods
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandInteraction.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandInteractionOption.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandInteractionOptionsProvider.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandOptionType.java
  javacord-api/src/main/java/org/javacord/api/util/DiscordRegexPattern.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandInteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandInteractionOptionImpl.java
Labels: high priority

#694 Bugfix: Do not request identify ratelimit on resume
  javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java
Labels: bug, medium priority

#786 General component fixes
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/Messageable.java
  javacord-api/src/main/java/org/javacord/api/entity/message/WebhookMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/ActionRow.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/ActionRowBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/Button.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/ButtonBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/internal/ActionRowBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/internal/ButtonBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/message/internal/MessageBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandOption.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandOptionChoice.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissions.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandPermissionsUpdater.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandUpdater.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilderBase.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/ActionRowImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/ButtonImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/ComponentImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/internal/ActionRowBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/internal/ButtonBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionMessageBuilderBaseImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionOriginalResponseUpdaterImpl.java
Labels: high priority

#785 NSFW Level for Guilds (servers).
  javacord-api/src/main/java/org/javacord/api/entity/server/NsfwLevel.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerChangeNsfwLevelEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerChangeNsfwLevelListener.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/event/server/ServerChangeNsfwLevelEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildUpdateHandler.java
Labels: low priority

#787 Add slash commands example to the README
  .github/README_template.md
Labels: high priority

#742 Fixes not working UserChangeXY events
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildMemberUpdateHandler.java
Labels: bug, high priority

#791 Add specific events for interactions
  javacord-api/src/main/java/org/javacord/api/event/interaction/ApplicationCommandCreateEvent.java
  javacord-api/src/main/java/org/javacord/api/event/interaction/ButtonClickEvent.java
  javacord-api/src/main/java/org/javacord/api/event/interaction/MessageComponentCreateEvent.java
  javacord-api/src/main/java/org/javacord/api/interaction/Interaction.java
  javacord-api/src/main/java/org/javacord/api/listener/interaction/ApplicationCommandCreateListener.java
  javacord-api/src/main/java/org/javacord/api/listener/interaction/ButtonClickListener.java
  javacord-api/src/main/java/org/javacord/api/listener/interaction/MessageComponentCreateListener.java
  javacord-core/src/main/java/org/javacord/core/event/interaction/ApplicationCommandCreateEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/interaction/ButtonClickEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/interaction/MessageComponentCreateEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java
Labels: high priority

#688 Revert bad commit due to false-positive IDE warnings
  javacord-core/src/main/java/org/javacord/core/util/event/EventDispatcherBase.java
  javacord-core/src/main/java/org/javacord/core/util/logging/ExceptionLoggerDelegateImpl.java
Labels: low priority

#793 Fix for ephemeral messages containing components
  javacord-api/src/main/java/org/javacord/api/interaction/MessageComponentInteractionBase.java
  javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/MessageComponentInteractionImpl.java
Labels: high priority
