Repository Javacord/Javacord, pull requests merged in 2021-07, with the labels that each got.

#801 Fix NPE when invoking a slash command in DMs and fix for #795
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
Labels: high priority

#816 Add option to control user cache
  gradle.properties
  javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
  javacord-api/src/main/java/org/javacord/api/internal/DiscordApiBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
Labels: breaking-change, medium priority

#770 Remove CircleCI
  .circleci/config.yml
Labels: low priority

#684 Added Get Guild Member endpoint
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
Labels: medium priority
