Repository Javacord/Javacord, pull requests merged in 2021-12, with the labels that each got.

#919 Fix inconsistency in slash command option naming
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandInteractionOption.java
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandInteractionOptionsProvider.java
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOption.java
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOptionType.java
  javacord-api/src/main/java/org/javacord/api/interaction/internal/SlashCommandOptionBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionOptionImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandOptionImpl.java
Labels: breaking-change

#921 Fix SlashCommandInteractionOptionImpl#getUserValue NPE
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionOptionImpl.java
Labels: bug

#922 Update log4j-api and recommended log4j-core version
  .github/README_template.md
  gradle/dependencies.gradle
Labels: high priority
