Repository Javacord/Javacord, pull requests merged in 2022-07, with the labels that each got.

#1045 Fix event queue and sticker memory leaks
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/util/event/EventDispatcherBase.java
Labels: high priority, breaking-change

#641 Change name of download methods for consistency
  javacord-api/src/main/java/org/javacord/api/entity/Attachment.java
  javacord-api/src/main/java/org/javacord/api/entity/message/embed/EmbedAuthor.java
  javacord-api/src/main/java/org/javacord/api/entity/message/embed/EmbedImage.java
  javacord-api/src/main/java/org/javacord/api/entity/message/embed/EmbedThumbnail.java
  javacord-core/src/main/java/org/javacord/core/entity/AttachmentImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/embed/EmbedAuthorImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/embed/EmbedImageImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/embed/EmbedThumbnailImpl.java
Labels: low priority

#638 Moved and added missing canXY() methods from VoiceChannel to ServerVoiceChannel
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/VoiceChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageAuthor.java
Labels: medium priority

#701 Added a new command framework
  .github/README_template.md
Labels: low priority
