Repository Javacord/Javacord, pull requests merged in 2022-10, with the labels that each got.

#1135 Disable signing library when building snapshot version on i.e. JitPack
  build.gradle.kts
Labels: hacktoberfest-accepted

#1137 Add support for Slash command mentions
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommand.java
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandOption.java
  javacord-api/src/main/java/org/javacord/api/util/DiscordRegexPattern.java
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandImpl.java
Labels: hacktoberfest-accepted

#1138 Add missing name to pre-release step workflow
  .github/workflows/pre-release-step.yml
Labels: :bug: bug, hacktoberfest-accepted

#1145 Correct error code in RestRequestResultErrorCode
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestResultErrorCode.java
Labels: :bug: bug

#1146 [Housekeeping] Update dead / old links to correct versions.
  javacord-api/src/main/java/org/javacord/api/DiscordApiBuilder.java
  javacord-api/src/main/java/org/javacord/api/Javacord.java
  javacord-api/src/main/java/org/javacord/api/entity/DiscordEntity.java
  javacord-api/src/main/java/org/javacord/api/entity/activity/ActivityType.java
  javacord-api/src/main/java/org/javacord/api/entity/intent/Intent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerBecomesAvailableEvent.java
  javacord-api/src/main/java/org/javacord/api/event/server/ServerBecomesUnavailableEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerBecomesAvailableListener.java
  javacord-api/src/main/java/org/javacord/api/listener/server/ServerBecomesUnavailableListener.java
  javacord-core/src/main/java/org/javacord/core/entity/webhook/WebhookUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioPacket.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/AudioUdpSocket.java
  javacord-core/src/main/java/org/javacord/core/util/gateway/WebSocketCloseCode.java
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/GuildMemberUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestHttpResponseCode.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequestResultErrorCode.java
Labels: improvement

#1136 Fix ThreadListSyncHandler
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/thread/ThreadListSyncHandler.java
Labels: :bug: bug, hacktoberfest-accepted

#1147 Remove deprecated methods
  javacord-api/src/main/java/org/javacord/api/entity/ApplicationInfo.java
  javacord-api/src/main/java/org/javacord/api/entity/Attachment.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/VoiceChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageAuthor.java
  javacord-api/src/main/java/org/javacord/api/entity/message/embed/EmbedAuthor.java
  javacord-api/src/main/java/org/javacord/api/entity/message/embed/EmbedImage.java
  javacord-api/src/main/java/org/javacord/api/entity/message/embed/EmbedThumbnail.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
Labels: :hammer: breaking-change

#1139 Add the ability to listen for replies to specific messages
  javacord-api/src/main/java/org/javacord/api/event/message/MessageReplyEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/message/MessageReplyListener.java
  javacord-core/src/main/java/org/javacord/core/event/message/MessageReplyEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
Labels: improvement

#1150 Add support for Select Menus v2
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/ComponentType.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/LowLevelComponent.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/SelectMenu.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/SelectMenuBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/internal/SelectMenuBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/SelectMenuInteraction.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/ActionRowImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/SelectMenuImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/internal/ActionRowBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/internal/SelectMenuBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/SelectMenuInteractionImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/interaction/InteractionCreateHandler.java
Labels: improvement, :hammer: breaking-change

#1155 added get thread member endpoint
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannel.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerThreadChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/util/rest/RestEndpoint.java
Labels: improvement

#1157 Changes to SlashCommand#getFullCommandName and getMentionTag
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommand.java
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandImpl.java
Labels: :hammer: breaking-change

#1156 Change get and request sticker string id parse methods to be more consistent
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
Labels: improvement

#1166 Add unicode emoji to SelectMenuOptionBuilder
  javacord-api/src/main/java/org/javacord/api/entity/message/component/SelectMenuOption.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/SelectMenuOptionBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/message/component/internal/SelectMenuOptionBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/entity/message/component/internal/SelectMenuOptionBuilderDelegateImpl.java
Labels: improvement

#1168 Fix MessageUpdater#replaceMessage not removing attachments
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java
Labels: :bug: bug

#1172 add intent to example in README
  .github/README_template.md
Labels: 📖documentation

#1176 Add ApplicationCommandInteraction#getRegisteredCommandServerId
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandInteraction.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandInteractionImpl.java
Labels: improvement

#1175 Add new Javacord compatible library "Discord Interaction Handler"
  .github/README_template.md
Labels: 📖documentation
