Repository Javacord/Javacord, pull requests merged in 2022-03, with the labels that each got.

#966 Fix issues with passing null as param in ServerThreadChannelBuilder#setInvitableFlag
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannelBuilder.java
Labels: bug

#971 Bugfix: URL-Encode audit log reason header
  javacord-core/src/main/java/org/javacord/core/util/rest/RestRequest.java
Labels: bug, medium priority

#961 Convert InteractionCallbackDataFlag back to MessageFlag
  javacord-api/src/main/java/org/javacord/api/entity/message/MessageFlag.java
  javacord-api/src/main/java/org/javacord/api/entity/message/internal/InteractionMessageBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionCallbackDataFlag.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/callback/InteractionMessageBuilderBase.java
  javacord-core/src/main/java/org/javacord/core/entity/message/InteractionMessageBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionMessageBuilderBaseImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/InteractionOriginalResponseUpdaterImpl.java
Labels: breaking-change

#981 Add a check if the `nsfw` field is present for ChannelCategory updates
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
Labels: bug
