Repository Javacord/Javacord, pull requests merged in 2022-01, with the labels that each got.

#931 Update server count of Yunite
  .github/README_template.md
Labels: low priority

#940 Fix method signatures of bulk overwrite application command methods
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
Labels: bug

#941 Update log4j to 1.17.1
  .github/README_template.md
  gradle/dependencies.gradle
Labels: high priority

#762 Adjusted user flags to the current existing ones
  javacord-api/src/main/java/org/javacord/api/entity/user/UserFlag.java
Labels: low priority, breaking-change

#731 Fixed getSlowmodeDelayInSeconds returning the reversed result
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
Labels: low priority, breaking-change

#847 Removed deprecated methods.
  javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
  javacord-api/src/main/java/org/javacord/api/util/ratelimit/LocalRatelimiter.java
Labels: breaking-change

#880 Remove SafeSpecializable as it breaks the contract of the parent interface and makes no sense actually
  javacord-api/src/main/java/org/javacord/api/interaction/Interaction.java
  javacord-api/src/main/java/org/javacord/api/interaction/MessageComponentInteraction.java
  javacord-api/src/main/java/org/javacord/api/util/SafeSpecializable.java
Labels: breaking-change

#882 Remove deprecated slash command option methods
  javacord-api/src/main/java/org/javacord/api/interaction/SlashCommandInteractionOptionsProvider.java
Labels: breaking-change

#952 Rename PermissionType#READ_MESSAGES to VIEW_CHANNEL
  gradle.properties
  javacord-api/src/main/java/org/javacord/api/entity/channel/Channel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/RegularServerChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
  javacord-api/src/main/java/org/javacord/api/entity/permission/PermissionType.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
Labels: breaking-change

#953 Fix check for resolved structure in wrong JsonNode in SlashCommandInteractionImpl
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandInteractionImpl.java
Labels: bug
