Repository Javacord/Javacord, pull requests merged in 2022-11, with the labels that each got.

#1177 Deprecate ApplicationCommand delete methods
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
Labels: improvement

#1178 Fix:Wrong links in readme
  .github/README_template.md
Labels: 📖documentation

#1167 Change how the delete_message_seconds field is set when banning a user
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
Labels: :bug: bug

#1182 Throw an exception when accessing the message content
  javacord-core/src/main/java/org/javacord/core/entity/message/MessageImpl.java
Labels: :hammer: breaking-change

#1170 Fixes for ServerVoiceChannel audio connection
  javacord-core/src/main/java/org/javacord/core/util/handler/guild/VoiceStateUpdateHandler.java
Labels: :bug: bug, :headphones: audio

#1192 Improvement to the generateChangelog gradle task
  gradle/generate-changelog.gradle.kts
Labels: improvement

#1193 added support for nsfw commands
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommand.java
  javacord-api/src/main/java/org/javacord/api/interaction/ApplicationCommandBuilder.java
  javacord-api/src/main/java/org/javacord/api/interaction/internal/ApplicationCommandBuilderDelegate.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/ApplicationCommandImpl.java
  javacord-core/src/main/java/org/javacord/core/interaction/SlashCommandImpl.java
Labels: improvement
