Repository Javacord/Javacord, pull requests merged in 2023-08, with the labels that each got.

#1253 Use sets instead of lists for user roles collections in server updater
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerUpdaterDelegateImpl.java
Labels: :bug: bug

#1251 Fixed a cache corruption issue when receiving ephemeral messages in text-in-voice channels and introduce TextableRegularServerChannel as entity
  gradle/listener-manager-generation.gradle
  javacord-api/src/main/java/org/javacord/api/DiscordApi.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ChannelType.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannelBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannelUpdater.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannelBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannelUpdater.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextableRegularServerChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextableRegularServerChannelBuilder.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextableRegularServerChannelUpdater.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerTextChannelBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerTextChannelUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerVoiceChannelBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerVoiceChannelUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/TextableRegularServerChannelBuilderDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/TextableRegularServerChannelUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
  javacord-api/src/main/java/org/javacord/api/event/channel/server/text/WebhooksUpdateEvent.java
  javacord-api/src/main/java/org/javacord/api/event/channel/server/textable/TextableRegularServerChannelEvent.java
  javacord-api/src/main/java/org/javacord/api/listener/channel/server/ServerChannelAttachableListener.java
  javacord-api/src/main/java/org/javacord/api/listener/channel/server/text/WebhooksUpdateListener.java
  javacord-api/src/main/java/org/javacord/api/listener/channel/server/textable/TextableRegularServerChannelAttachableListener.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactory.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactoryDelegate.java
  javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerTextChannelUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/TextableRegularServerChannelBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/TextableRegularServerChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/TextableRegularServerChannelUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/server/ServerImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/server/text/WebhooksUpdateEventImpl.java
  javacord-core/src/main/java/org/javacord/core/event/channel/server/textable/TextableRegularServerChannelEventImpl.java
  javacord-core/src/main/java/org/javacord/core/util/DelegateFactoryDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/ChannelUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/channel/WebhooksUpdateHandler.java
  javacord-core/src/main/java/org/javacord/core/util/handler/message/MessageCreateHandler.java
Labels: :bug: bug, :hammer: breaking-change

#1224 Polish GHA configs
  .github/workflows/checkstyle.yml
  .github/workflows/main.yml
  .github/workflows/pre-release-step.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: improvement
