Repository Javacord/Javacord, pull requests merged in 2023-02, with the labels that each got.

#1208 added canYouTimeoutUser && canTimeoutUser && canYouTimeoutUsers
  javacord-api/src/main/java/org/javacord/api/entity/server/Server.java
Labels: improvement

#1207 Update Jackson.
  javacord-core/build.gradle.kts
Labels: :bug: bug

#1014 Add text in voice channels
  gradle.properties
  javacord-api/src/main/java/org/javacord/api/entity/channel/Channel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/PrivateChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerTextChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerThreadChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/ServerVoiceChannelUpdater.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/TextableRegularServerChannel.java
  javacord-api/src/main/java/org/javacord/api/entity/channel/internal/ServerVoiceChannelUpdaterDelegate.java
  javacord-api/src/main/java/org/javacord/api/entity/message/Message.java
  javacord-api/src/main/java/org/javacord/api/entity/webhook/WebhookBuilder.java
  javacord-api/src/main/java/org/javacord/api/event/channel/TextChannelEvent.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactory.java
  javacord-api/src/main/java/org/javacord/api/util/internal/DelegateFactoryDelegate.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/channel/ServerVoiceChannelUpdaterDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/entity/webhook/WebhookBuilderDelegateImpl.java
  javacord-core/src/main/java/org/javacord/core/util/DelegateFactoryDelegateImpl.java
Labels: improvement, high priority, :hammer: breaking-change
